USE iei_172_n2;

INSERT INTO marcas (nombre_marca, pais_origen) VALUES
('Toyota', 'Japón'),
('Honda', 'Japón'),
('Nissan', 'Japón'),
('Mazda', 'Japón'),
('Subaru', 'Japón'),
('Mitsubishi', 'Japón'),
('Suzuki', 'Japón'),
('Lexus', 'Japón'),
('Infiniti', 'Japón'),
('Acura', 'Japón'),
('Ford', 'Estados Unidos'),
('Chevrolet', 'Estados Unidos'),
('Dodge', 'Estados Unidos'),
('Tesla', 'Estados Unidos'),
('Jeep', 'Estados Unidos'),
('Cadillac', 'Estados Unidos'),
('GMC', 'Estados Unidos'),
('Lincoln', 'Estados Unidos'),
('Buick', 'Estados Unidos'),
('Chrysler', 'Estados Unidos'),
('Volkswagen', 'Alemania'),
('BMW', 'Alemania'),
('Mercedes-Benz', 'Alemania'),
('Audi', 'Alemania'),
('Porsche', 'Alemania'),
('Opel', 'Alemania'),
('Smart', 'Alemania'),
('Maybach', 'Alemania'),
('Peugeot', 'Francia'),
('Renault', 'Francia'),
('Citroën', 'Francia'),
('DS Automobiles', 'Francia'),
('Bugatti', 'Francia'),
('Fiat', 'Italia'),
('Ferrari', 'Italia'),
('Lamborghini', 'Italia'),
('Maserati', 'Italia'),
('Alfa Romeo', 'Italia'),
('Lancia', 'Italia'),
('Pagani', 'Italia'),
('Volvo', 'Suecia'),
('Saab', 'Suecia'),
('Koenigsegg', 'Suecia'),
('Hyundai', 'Corea del Sur'),
('Kia', 'Corea del Sur'),
('Genesis', 'Corea del Sur'),
('Daewoo', 'Corea del Sur'),
('Tata', 'India'),
('Mahindra', 'India'),
('Geely', 'China'),
('BYD', 'China'),
('Changan', 'China'),
('Great Wall', 'China'),
('NIO', 'China'),
('XPeng', 'China'),
('Hongqi', 'China'),
('SEAT', 'España'),
('Cupra', 'España'),
('Aston Martin', 'Reino Unido'),
('Jaguar', 'Reino Unido'),
('Land Rover', 'Reino Unido'),
('Mini', 'Reino Unido'),
('Bentley', 'Reino Unido'),
('Rolls-Royce', 'Reino Unido'),
('McLaren', 'Reino Unido'),
('Holden', 'Australia'),
('HSV', 'Australia'),
('Dacia', 'Rumania'),
('Skoda', 'República Checa');

INSERT INTO comunas(codigo_comuna,nombre_comuna) VALUES
('15101','Arica'),
('15102','Camarones'),
('15201','Putre'),
('15202','General Lagos'),
('01101','Iquique'),
('01402','Camiña'),
('01403','Colchane'),
('01404','Huara'),
('01405','Pica'),
('01401','Pozo Almonte'),
('01107','Alto Hospicio'),
('02101','Antofagasta'),
('02102','Mejillones'),
('02103','Sierra Gorda'),
('02104','Taltal'),
('02201','Calama'),
('02202','Ollagüe'),
('02203','San Pedro de Atacama'),
('02301','Tocopilla'),
('02302','María Elena'),
('03101','Copiapó'),
('03102','Caldera'),
('03103','Tierra Amarilla'),
('03201','Chañaral'),
('03202','Diego de Almagro'),
('03301','Vallenar'),
('03302','Alto del Carmen'),
('03303','Freirina'),
('03304','Huasco'),
('04101','La Serena'),
('04102','Coquimbo'),
('04103','Andacollo'),
('04104','La Higuera'),
('04105','Paiguano'),
('04106','Vicuña'),
('04201','Illapel'),
('04202','Canela'),
('04203','Los Vilos'),
('04204','Salamanca'),
('04301','Ovalle'),
('04302','Combarbalá'),
('04303','Monte Patria'),
('04304','Punitaqui'),
('04305','Río Hurtado'),
('05101','Valparaíso'),
('05102','Casablanca'),
('05103','Concón'),
('05104','Juan Fernández'),
('05105','Puchuncaví'),
('05801','Quilpué'),
('05107','Quintero'),
('05804','Villa Alemana'),
('05109','Viña del Mar'),
('05201','Isla de Pascua'),
('05301','Los Andes'),
('05302','Calle Larga'),
('05303','Rinconada'),
('05304','San Esteban'),
('05401','La Ligua'),
('05402','Cabildo'),
('05403','Papudo'),
('05404','Petorca'),
('05405','Zapallar'),
('05501','Quillota'),
('05502','Calera'),
('05503','Hijuelas'),
('05504','La Cruz'),
('05802','Limache'),
('05506','Nogales'),
('05803','Olmué'),
('05601','San Antonio'),
('05602','Algarrobo'),
('05603','Cartagena'),
('05604','El Quisco'),
('05605','El Tabo'),
('05606','Santo Domingo'),
('05701','San Felipe'),
('05702','Catemu'),
('05703','Llaillay'),
('05704','Panquehue'),
('05705','Putaendo'),
('05706','Santa María'),
('06101','Rancagua'),
('06102','Codegua'),
('06103','Coinco'),
('06104','Coltauco'),
('06105','Doñihue'),
('06106','Graneros'),
('06107','Las Cabras'),
('06108','Machalí'),
('06109','Malloa'),
('06110','Mostazal'),
('06111','Olivar'),
('06112','Peumo'),
('06113','Pichidegua'),
('06114','Quinta de Tilcoco'),
('06115','Rengo'),
('06116','Requínoa'),
('06117','San Vicente'),
('06201','Pichilemu'),
('06202','La Estrella'),
('06203','Litueche'),
('06204','Marchihue'),
('06205','Navidad'),
('06206','Paredones'),
('06301','San Fernando'),
('06302','Chépica'),
('06303','Chimbarongo'),
('06304','Lolol'),
('06305','Nancagua'),
('06306','Palmilla'),
('06307','Peralillo'),
('06308','Placilla'),
('06309','Pumanque'),
('06310','Santa Cruz'),
('07101','Talca'),
('07102','Constitución'),
('07103','Curepto'),
('07104','Empedrado'),
('07105','Maule'),
('07106','Pelarco'),
('07107','Pencahue'),
('07108','Río Claro'),
('07109','San Clemente'),
('07110','San Rafael'),
('07201','Cauquenes'),
('07202','Chanco'),
('07203','Pelluhue'),
('07301','Curicó'),
('07302','Hualañé'),
('07303','Licantén'),
('07304','Molina'),
('07305','Rauco'),
('07306','Romeral'),
('07307','Sagrada Familia'),
('07308','Teno'),
('07309','Vichuquén'),
('07401','Linares'),
('07402','Colbún'),
('07403','Longaví'),
('07404','Parral'),
('07405','Retiro'),
('07406','San Javier'),
('07407','Villa Alegre'),
('07408','Yerbas Buenas'),
('08101','Concepción'),
('08102','Coronel'),
('08103','Chiguayante'),
('08104','Florida'),
('08105','Hualqui'),
('08106','Lota'),
('08107','Penco'),
('08108','San Pedro de la Paz'),
('08109','Santa Juana'),
('08110','Talcahuano'),
('08111','Tomé'),
('08112','Hualpén'),
('08201','Lebu'),
('08202','Arauco'),
('08203','Cañete'),
('08204','Contulmo'),
('08205','Curanilahue'),
('08206','Los Álamos'),
('08207','Tirúa'),
('08301','Los Ángeles'),
('08302','Antuco'),
('08303','Cabrero'),
('08304','Laja'),
('08305','Mulchén'),
('08306','Nacimiento'),
('08307','Negrete'),
('08308','Quilaco'),
('08309','Quilleco'),
('08310','San Rosendo'),
('08311','Santa Bárbara'),
('08312','Tucapel'),
('08313','Yumbel'),
('08314','Alto Biobío'),
('08401','Chillán'),
('08402','Bulnes'),
('08403','Cobquecura'),
('08404','Coelemu'),
('08405','Coihueco'),
('08406','Chillán Viejo'),
('08407','El Carmen'),
('08408','Ninhue'),
('08409','Ñiquén'),
('08410','Pemuco'),
('08411','Pinto'),
('08412','Portezuelo'),
('08413','Quillón'),
('08414','Quirihue'),
('08415','Ránquil'),
('08416','San Carlos'),
('08417','San Fabián'),
('08418','San Ignacio'),
('08419','San Nicolás'),
('08420','Treguaco'),
('08421','Yungay'),
('09101','Temuco'),
('09102','Carahue'),
('09103','Cunco'),
('09104','Curarrehue'),
('09105','Freire'),
('09106','Galvarino'),
('09107','Gorbea'),
('09108','Lautaro'),
('09109','Loncoche'),
('09110','Melipeuco'),
('09111','Nueva Imperial'),
('09112','Padre Las Casas'),
('09113','Perquenco'),
('09114','Pitrufquén'),
('09115','Pucón'),
('09116','Saavedra'),
('09117','Teodoro Schmidt'),
('09118','Toltén'),
('09119','Vilcún'),
('09120','Villarrica'),
('09121','Cholchol'),
('09201','Angol'),
('09202','Collipulli'),
('09203','Curacautín'),
('09204','Ercilla'),
('09205','Lonquimay'),
('09206','Los Sauces'),
('09207','Lumaco'),
('09208','Purén'),
('09209','Renaico'),
('09210','Traiguén'),
('09211','Victoria'),
('14101','Valdivia'),
('14102','Corral'),
('14202','Futrono'),
('14201','La Unión'),
('14203','Lago Ranco'),
('14103','Lanco'),
('14104','Los Lagos'),
('14105','Máfil'),
('14106','Mariquina'),
('14107','Paillaco'),
('14108','Panguipulli'),
('14204','Río Bueno'),
('10101','Puerto Montt'),
('10102','Calbuco'),
('10103','Cochamó'),
('10104','Fresia'),
('10105','Frutillar'),
('10106','Los Muermos'),
('10107','Llanquihue'),
('10108','Maullín'),
('10109','Puerto Varas'),
('10201','Castro'),
('10202','Ancud'),
('10203','Chonchi'),
('10204','Curaco de Vélez'),
('10205','Dalcahue'),
('10206','Puqueldón'),
('10207','Queilén'),
('10208','Quellón'),
('10209','Quemchi'),
('10210','Quinchao'),
('10301','Osorno'),
('10302','Puerto Octay'),
('10303','Purranque'),
('10304','Puyehue'),
('10305','Río Negro'),
('10306','San Juan de la Costa'),
('10307','San Pablo'),
('10401','Chaitén'),
('10402','Futaleufú'),
('10403','Hualaihué'),
('10404','Palena'),
('11101','Coihaique'),
('11102','Lago Verde'),
('11201','Aisén'),
('11202','Cisnes'),
('11203','Guaitecas'),
('11301','Cochrane'),
('11302','O''Higgins'),
('11303','Tortel'),
('11401','Chile Chico'),
('11402','Río Ibáñez'),
('12101','Punta Arenas'),
('12102','Laguna Blanca'),
('12103','Río Verde'),
('12104','San Gregorio'),
('12201','Cabo de Hornos'),
('12202','Antártica'),
('12301','Porvenir'),
('12302','Primavera'),
('12303','Timaukel'),
('12401','Natales'),
('12402','Torres del Paine'),
('13101','Santiago'),
('13102','Cerrillos'),
('13103','Cerro Navia'),
('13104','Conchalí'),
('13105','El Bosque'),
('13106','Estación Central'),
('13107','Huechuraba'),
('13108','Independencia'),
('13109','La Cisterna'),
('13110','La Florida'),
('13111','La Granja'),
('13112','La Pintana'),
('13113','La Reina'),
('13114','Las Condes'),
('13115','Lo Barnechea'),
('13116','Lo Espejo'),
('13117','Lo Prado'),
('13118','Macul'),
('13119','Maipú'),
('13120','Ñuñoa'),
('13121','Pedro Aguirre Cerda'),
('13122','Peñalolén'),
('13123','Providencia'),
('13124','Pudahuel'),
('13125','Quilicura'),
('13126','Quinta Normal'),
('13127','Recoleta'),
('13128','Renca'),
('13129','San Joaquín'),
('13130','San Miguel'),
('13131','San Ramón'),
('13132','Vitacura'),
('13201','Puente Alto'),
('13202','Pirque'),
('13203','San José de Maipo'),
('13301','Colina'),
('13302','Lampa'),
('13303','Tiltil'),
('13401','San Bernardo'),
('13402','Buin'),
('13403','Calera de Tango'),
('13404','Paine'),
('13501','Melipilla'),
('13502','Alhué'),
('13503','Curacaví'),
('13504','María Pinto'),
('13505','San Pedro'),
('13601','Talagante'),
('13602','El Monte'),
('13603','Isla de Maipo'),
('13604','Padre Hurtado'),
('13605','Peñaflor');

INSERT INTO tipos_mecanico(tipo_mecanico,descripcion_tipo_mecanico) VALUES
('Mecánica General','Mantenimiento y reparación de los componentes mecánicos generales. Motor, transmisión y sistemas de lubricación.'),
('Eléctrico y Electrónico','Sistemas eléctricos y electrónicos. Arranque, carga, iluminación y diagnóstico de fallos electrónicos.'),
('Transmición','Reparaciones de transmisión.'),
('Frenos','Reparación y mantenimiento del sistema de frenos.'),
('Neumáticos','Cuidado de neumáticos. Reparación, reemplazo y balanceo.'),
('Carrocería','Reparaciones de carrocería. Acabados interiores y exteriores.'),
('Refrigeración','Mantenimiento y reparación del sistema de enfriamiento del motor.');

INSERT INTO combustibles (tipo_combustible,descripcion_tipo_combustible) VALUES
('Gasolina','Obtenido del petróleo crudo, utilizado en motores de combustión con chispa. Se clasifica por su nivel de octanaje, que indica su resistencia a la detonación.'),
('Diésel','Hidrocarburo líquido derivado del petróleo, usado en motores de compresión, más comunes en camiones y autobuses.'),
('Gas Licuado','Una mezcla de propano y butano, alternativa más limpia y económica a la gasolina y el diésel.'),
('Gas Natural','Gas metano en estado gaseoso sometido a alta presión, conocido por su combustión limpia y menor impacto ambiental.'),
('Biodiésel','Combustible de origen vegetal que se mezcla con el diésel convencional, reduciendo las emisiones contaminantes.'),
('Etanol','Tipo de bioalcohol que se mezcla con la gasolina, aumentando su octanaje y mejorando su calidad como combustible.'),
('Electricidad','En los vehículos eléctricos (EVs), se reemplaza el motor de combustión por un motor eléctrico y el tanque de combustible por una batería. Son vehículos cero emisiones.'),
('Hidrógeno','Tecnología futura prometedora, que al utilizar una pila de combustible produce electricidad sin generar más que vapor de agua.'),
('Híbrido','Combinan un motor de combustión interna con uno o más motores eléctricos para mejorar la eficiencia y reducir las emisiones. ');

INSERT INTO modelos (nombre_modelo, tipo_combustible, puertas, descripcion_modelo) VALUES
('Toyota Corolla', (SELECT id FROM combustibles WHERE tipo_combustible = 'Gasolina'), 4, 'Sedán compacto confiable y eficiente de Toyota'),
('Toyota Hilux', (SELECT id FROM combustibles WHERE tipo_combustible = 'Diésel'), 4, 'Camioneta robusta ideal para trabajo y todo terreno'),
('Toyota RAV4', (SELECT id FROM combustibles WHERE tipo_combustible = 'Híbrido'), 5, 'SUV familiar eficiente con motorización híbrida'),
('Honda Civic', (SELECT id FROM combustibles WHERE tipo_combustible = 'Gasolina'), 4, 'Sedán de Honda con excelente rendimiento y diseño moderno'),
('Honda CR-V', (SELECT id FROM combustibles WHERE tipo_combustible = 'Gasolina'), 5, 'SUV espacioso y confiable de Honda'),
('Honda Accord', (SELECT id FROM combustibles WHERE tipo_combustible = 'Híbrido'), 4, 'Sedán mediano cómodo y eficiente'),
('Nissan Sentra', (SELECT id FROM combustibles WHERE tipo_combustible = 'Gasolina'), 4, 'Sedán compacto de Nissan con diseño actual'),
('Nissan Frontier', (SELECT id FROM combustibles WHERE tipo_combustible = 'Diésel'), 4, 'Camioneta resistente para trabajo y aventura'),
('Nissan Leaf', (SELECT id FROM combustibles WHERE tipo_combustible = 'Electricidad'), 5, 'Hatchback 100% eléctrico pionero de Nissan'),
('Ford Focus', (SELECT id FROM combustibles WHERE tipo_combustible = 'Gasolina'), 5, 'Compacto versátil y dinámico'),
('Ford F-150', (SELECT id FROM combustibles WHERE tipo_combustible = 'Gasolina'), 4, 'Camioneta full size líder en ventas en EE.UU.'),
('Ford Mustang', (SELECT id FROM combustibles WHERE tipo_combustible = 'Gasolina'), 2, 'Coupé deportivo icónico de Ford'),
('Chevrolet Onix', (SELECT id FROM combustibles WHERE tipo_combustible = 'Gasolina'), 4, 'Sedán compacto popular en Latinoamérica'),
('Chevrolet Silverado', (SELECT id FROM combustibles WHERE tipo_combustible = 'Gasolina'), 4, 'Camioneta grande de Chevrolet'),
('Chevrolet Camaro', (SELECT id FROM combustibles WHERE tipo_combustible = 'Gasolina'), 2, 'Deportivo americano clásico'),
('Volkswagen Golf', (SELECT id FROM combustibles WHERE tipo_combustible = 'Gasolina'), 5, 'Hatchback versátil y de excelente manejo'),
('Volkswagen Polo', (SELECT id FROM combustibles WHERE tipo_combustible = 'Gasolina'), 5, 'Compacto urbano confiable'),
('Volkswagen Tiguan', (SELECT id FROM combustibles WHERE tipo_combustible = 'Gasolina'), 5, 'SUV de tamaño medio con diseño sobrio'),
('BMW Serie 3', (SELECT id FROM combustibles WHERE tipo_combustible = 'Gasolina'), 4, 'Sedán deportivo de gama media con gran manejo'),
('BMW X5', (SELECT id FROM combustibles WHERE tipo_combustible = 'Híbrido'), 5, 'SUV de lujo con tecnología avanzada'),
('BMW i4', (SELECT id FROM combustibles WHERE tipo_combustible = 'Electricidad'), 5, 'Sedán eléctrico de alto rendimiento'),
('Mercedes-Benz Clase C', (SELECT id FROM combustibles WHERE tipo_combustible = 'Gasolina'), 4, 'Sedán de lujo con diseño elegante'),
('Mercedes-Benz Clase E', (SELECT id FROM combustibles WHERE tipo_combustible = 'Híbrido'), 4, 'Sedán ejecutivo con gran confort'),
('Mercedes-Benz GLC', (SELECT id FROM combustibles WHERE tipo_combustible = 'Gasolina'), 5, 'SUV de lujo mediano'),
('Audi A3', (SELECT id FROM combustibles WHERE tipo_combustible = 'Gasolina'), 4, 'Sedán compacto premium de Audi'),
('Audi Q5', (SELECT id FROM combustibles WHERE tipo_combustible = 'Híbrido'), 5, 'SUV premium con equilibrio entre confort y potencia'),
('Audi e-tron', (SELECT id FROM combustibles WHERE tipo_combustible = 'Electricidad'), 5, 'SUV eléctrico de gama alta de Audi'),
('Hyundai Elantra', (SELECT id FROM combustibles WHERE tipo_combustible = 'Gasolina'), 4, 'Sedán mediano con diseño moderno'),
('Hyundai Tucson', (SELECT id FROM combustibles WHERE tipo_combustible = 'Gasolina'), 5, 'SUV popular de Hyundai con buen equipamiento'),
('Hyundai Ioniq 5', (SELECT id FROM combustibles WHERE tipo_combustible = 'Electricidad'), 5, 'SUV eléctrico innovador y futurista'),
('Kia Rio', (SELECT id FROM combustibles WHERE tipo_combustible = 'Gasolina'), 4, 'Compacto urbano económico de Kia'),
('Kia Sportage', (SELECT id FROM combustibles WHERE tipo_combustible = 'Gasolina'), 5, 'SUV mediano con gran diseño'),
('Kia EV6', (SELECT id FROM combustibles WHERE tipo_combustible = 'Electricidad'), 5, 'SUV eléctrico deportivo de Kia'),
('Tesla Model 3', (SELECT id FROM combustibles WHERE tipo_combustible = 'Electricidad'), 4, 'Sedán eléctrico más vendido de Tesla'),
('Tesla Model Y', (SELECT id FROM combustibles WHERE tipo_combustible = 'Electricidad'), 5, 'SUV eléctrico compacto de Tesla'),
('Tesla Model S', (SELECT id FROM combustibles WHERE tipo_combustible = 'Electricidad'), 4, 'Sedán eléctrico premium con gran autonomía'),
('Peugeot 208', (SELECT id FROM combustibles WHERE tipo_combustible = 'Gasolina'), 5, 'Hatchback urbano moderno'),
('Peugeot 3008', (SELECT id FROM combustibles WHERE tipo_combustible = 'Híbrido'), 5, 'SUV de diseño atractivo y eficiente'),
('Renault Clio', (SELECT id FROM combustibles WHERE tipo_combustible = 'Gasolina'), 5, 'Hatchback urbano clásico de Renault'),
('Renault Duster', (SELECT id FROM combustibles WHERE tipo_combustible = 'Gasolina'), 5, 'SUV accesible y robusto para la familia'),
('Fiat 500', (SELECT id FROM combustibles WHERE tipo_combustible = 'Gasolina'), 3, 'Pequeño urbano de estilo italiano'),
('Fiat Cronos', (SELECT id FROM combustibles WHERE tipo_combustible = 'Gasolina'), 4, 'Sedán compacto de producción regional'),
('Volvo XC60', (SELECT id FROM combustibles WHERE tipo_combustible = 'Híbrido'), 5, 'SUV de lujo sueco con gran seguridad'),
('Volvo C40 Recharge', (SELECT id FROM combustibles WHERE tipo_combustible = 'Electricidad'), 5, 'SUV eléctrico de diseño escandinavo'),
('Mazda3', (SELECT id FROM combustibles WHERE tipo_combustible = 'Gasolina'), 5, 'Hatchback con excelente comportamiento dinámico'),
('Mazda CX-5', (SELECT id FROM combustibles WHERE tipo_combustible = 'Gasolina'), 5, 'SUV mediano equilibrado y elegante'),
('Subaru Forester', (SELECT id FROM combustibles WHERE tipo_combustible = 'Gasolina'), 5, 'SUV con tracción integral y enfoque familiar'),
('Subaru Outback', (SELECT id FROM combustibles WHERE tipo_combustible = 'Gasolina'), 5, 'Crossover versátil con espíritu aventurero'),
('Ferrari 296 GTB', (SELECT id FROM combustibles WHERE tipo_combustible = 'Híbrido'), 2, 'Superdeportivo híbrido de Ferrari'),
('Lamborghini Huracán', (SELECT id FROM combustibles WHERE tipo_combustible = 'Gasolina'), 2, 'Superdeportivo italiano de altas prestaciones'),
('Porsche 911', (SELECT id FROM combustibles WHERE tipo_combustible = 'Gasolina'), 2, 'Deportivo legendario con motor trasero'),
('Porsche Taycan', (SELECT id FROM combustibles WHERE tipo_combustible = 'Electricidad'), 4, 'Sedán eléctrico de alto rendimiento de Porsche');