from .cliente import Cliente
from .combustible import Combustible
from .comuna import Comuna
from .direccion import Direccion
from .marca import Marca
from .mecanico_taller import MecanicoTaller
from .mecanico import Mecanico
from .modelo import Modelo
from .reparacion import Reparacion
from .taller import Taller
from .tipo_mecanico import TipoMecanico
from .tipo_vehiculo import TipoVehiculo
from .usuario import Usuario
from .vehiculo_cliente import VehiculoCliente
from .vehiculo import Vehiculo
